"""empty message

Revision ID: 519ee25ab402
Revises: 
Create Date: 2021-03-02 16:02:06.337610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519ee25ab402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_ojos', sa.String(length=250), nullable=True),
    sa.Column('color_piel', sa.String(length=250), nullable=True),
    sa.Column('color_cabello', sa.String(length=250), nullable=True),
    sa.Column('genero', sa.String(length=250), nullable=True),
    sa.Column('masa', sa.String(length=250), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=250), nullable=True),
    sa.Column('creacion', sa.String(length=250), nullable=True),
    sa.Column('editado', sa.String(length=250), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planeta',
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residentes', sa.String(length=250), nullable=True),
    sa.Column('periodo_orbital', sa.String(length=250), nullable=True),
    sa.Column('clima', sa.String(length=250), nullable=True),
    sa.Column('diametro', sa.String(length=250), nullable=True),
    sa.Column('gravedad', sa.String(length=250), nullable=True),
    sa.Column('poblacion', sa.String(length=250), nullable=True),
    sa.Column('periodo_rotacion', sa.String(length=250), nullable=True),
    sa.Column('superfice_acuatica', sa.String(length=250), nullable=True),
    sa.Column('terreno', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('primer_apellido', sa.String(length=250), nullable=True),
    sa.Column('segundo_apellido', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('personajes_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personajes_id'], ['Personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['Planeta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favoritos')
    op.drop_table('Usuario')
    op.drop_table('Planeta')
    op.drop_table('Personajes')
    # ### end Alembic commands ###
